# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49278c812755b53ae801a3086b6b19140e936142efe9f6be0157b38a698f4e1a739248080966a68b43b9c0ec9083ae5057d5e4647ae339db1568ac2052b5a788

test:
  secret_key_base: 0e6754d7090acc9b9de4d1c500dbb6efb0be96091a8912dcc064f51a3f42652d0967893aa3aef0bb0387d6705cb5bf61cb210ff8285f329856d299882f39301f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
